### ISSUE TITLE
Record Complete events not fired when call is ended

### ISSUE THREAD

**Issue by bklang** [rayo/rayo-server#18]
I have a call that is being recorded as soon as it answers.  I do not have control over when the call ends, yet I need to receive the Record Complete event to be able to get the recording.  It appears that the Complete event is never being sent by Rayo (PRISM):

```
[2012-03-14 17:47:52] TRACE Punchblock::Connection::XMPP: RECEIVING (presence) <presence from="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net" id="0620d168-9b9a-41b3-a723-691dbd7d8a62" to="usera@127.0.0.1">
  <offer xmlns="urn:xmpp:rayo:1" from="sip:bklang@sip2sip.info" to="sip:asdf@loadtest-ahn1-ext.testing.voxeolabs.net">
    <header name="Record-Route" value="&lt;sip:81.23.228.129;lr;ftag=urLRPiWQBMrgEnuIHhDCbPNO-rowXT9c;did=c29.69309ee3&gt;"/>
    <header name="Content-Length" value="414"/>
    <header name="To" value="&lt;sip:asdf@loadtest-ahn1-ext.testing.voxeolabs.net&gt;"/>
    <header name="Contact" value="&lt;sip:xfymengp@75.144.233.245:64761&gt;"/>
    <header name="Supported" value="100rel"/>
    <header name="User-Agent" value="Blink Pro 1.7.3 (MacOSX)"/>
    <header name="Max-Forwards" value="68"/>
    <header name="Allow" value="SUBSCRIBE"/>
    <header name="CSeq" value="13072 INVITE"/>
    <header name="Via" value="SIP/2.0/UDP 81.23.228.129;branch=z9hG4bK45b6.58121064.0"/>
    <header name="Call-ID" value="E-0LGzcUyIIlnxqNXXV2F1Yy9A-RS9jk"/>
    <header name="Content-Type" value="application/sdp"/>
    <header name="From" value="&quot;Ben Klang&quot; &lt;sip:bklang@sip2sip.info&gt;;tag=urLRPiWQBMrgEnuIHhDCbPNO-rowXT9c"/>
  </offer>
</presence>
[2012-03-14 17:47:52] DEBUG Adhearsion::Call: : Receiving message: #<Punchblock::Event::Offer to="sip:asdf@loadtest-ahn1-ext.testing.voxeolabs.net", from="sip:bklang@sip2sip.info", call_id="ztj99ye-lx7-v6lxsvdobtanb"
[2012-03-14 17:47:52] DEBUG Adhearsion::Call: ztj99ye-lx7-v6lxsvdobtanb: Executing command #<Punchblock::Command::Accept headers_hash={}, call_id=nil, component_id=nil>
[2012-03-14 17:47:52] TRACE Punchblock::Connection::XMPP: SENDING: (/Users/bklang/.rvm/gems/ruby-1.9.3-p125/bundler/gems/blather-b5e3d1c06b48/lib/blather/client/client.rb:149:in `write') <iq type="set" to="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net" id="blather0008"><accept xmlns="urn:xmpp:rayo:1"/></iq>
[2012-03-14 17:47:52] TRACE Punchblock::Connection::XMPP: RECEIVING (iq) <iq from="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net" id="blather0008" to="usera@127.0.0.1/morningside.local-43315" type="result"/>
[2012-03-14 17:47:52] DEBUG Adhearsion::Router: Call ztj99ye-lx7-v6lxsvdobtanb selected route "default" (#<Proc:0x00000103033988@/Users/bklang/src/loadtest/config/adhearsion.rb:40>)
[2012-03-14 17:47:52] DEBUG Adhearsion::Call: ztj99ye-lx7-v6lxsvdobtanb: Executing command #<Punchblock::Command::Answer headers_hash={}, call_id=nil, component_id=nil>
[2012-03-14 17:47:52] TRACE Punchblock::Connection::XMPP: SENDING: (/Users/bklang/.rvm/gems/ruby-1.9.3-p125/bundler/gems/blather-b5e3d1c06b48/lib/blather/client/client.rb:149:in `write') <iq type="set" to="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net" id="blather000a"><answer xmlns="urn:xmpp:rayo:1"/></iq>
[2012-03-14 17:47:52] TRACE Punchblock::Connection::XMPP: RECEIVING (iq) <iq from="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net" id="blather000a" to="usera@127.0.0.1/morningside.local-43315" type="result"/>
[2012-03-14 17:47:52] DEBUG Adhearsion::Call: ztj99ye-lx7-v6lxsvdobtanb: Receiving message: #<Punchblock::Event::Offer to="sip:asdf@loadtest-ahn1-ext.testing.voxeolabs.net", from="sip:bklang@sip2sip.info", call_id="ztj99ye-lx7-v6lxsvdobtanb"
[2012-03-14 17:47:52] DEBUG Adhearsion::Call: ztj99ye-lx7-v6lxsvdobtanb: Executing command #<Punchblock::Component::Record final_timeout=nil, format=nil, initial_timeout=nil, max_duration=nil, start_beep=false, start_paused=false, stop_beep=false, call_id=nil, component_id=nil>
[2012-03-14 17:47:52] TRACE Punchblock::Connection::XMPP: SENDING: (/Users/bklang/.rvm/gems/ruby-1.9.3-p125/bundler/gems/blather-b5e3d1c06b48/lib/blather/client/client.rb:149:in `write') <iq type="set" to="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net" id="blather000c"><record xmlns="urn:xmpp:rayo:record:1"/></iq>
[2012-03-14 17:47:52] TRACE Punchblock::Connection::XMPP: RECEIVING (iq) <iq from="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net" id="blather000c" to="usera@127.0.0.1/morningside.local-43315" type="result">
  <ref xmlns="urn:xmpp:rayo:1" id="ab2b0f00-f158-4f5f-8dc0-5f74cf12d43c"/>
</iq>
[2012-03-14 17:47:52] DEBUG Adhearsion::Call: ztj99ye-lx7-v6lxsvdobtanb: Executing command #<Punchblock::Command::Hangup headers_hash={}, call_id=nil, component_id=nil>
[2012-03-14 17:47:52] TRACE Punchblock::Connection::XMPP: SENDING: (/Users/bklang/.rvm/gems/ruby-1.9.3-p125/bundler/gems/blather-b5e3d1c06b48/lib/blather/client/client.rb:149:in `write') <iq type="set" to="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net" id="blather000e"><hangup xmlns="urn:xmpp:rayo:1"/></iq>
[2012-03-14 17:47:53] TRACE Punchblock::Connection::XMPP: RECEIVING (iq) <iq from="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net" id="blather000e" to="usera@127.0.0.1/morningside.local-43315" type="result"/>
[2012-03-14 17:47:53] TRACE Punchblock::Connection::XMPP: RECEIVING (presence) <presence from="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net/ab2b0f00-f158-4f5f-8dc0-5f74cf12d43c" id="57401fe8-8726-4ae0-988a-5b5ba5494573" to="usera@127.0.0.1">
  <complete xmlns="urn:xmpp:rayo:ext:1">
    <hangup xmlns="urn:xmpp:rayo:ext:complete:1"/>
    <recording xmlns="urn:xmpp:rayo:record:complete:1" duration="100" size="3898" uri="file:/tmp/rayo4781399191081109846.wav"/>
  </complete>
</presence>
[2012-03-14 17:47:53] TRACE Punchblock::Connection::XMPP: RECEIVING (presence) <presence from="ztj99ye-lx7-v6lxsvdobtanb@loadtest-ahn1.testing.voxeolabs.net" id="3e6624ad-226d-4147-9710-bf168886e0cc" to="usera@127.0.0.1">
  <end xmlns="urn:xmpp:rayo:1">
    <hangup/>
  </end>
</presence>
[2012-03-14 17:47:53] DEBUG Adhearsion::Call: ztj99ye-lx7-v6lxsvdobtanb: Receiving message: #<Punchblock::Event::Complete reason=#<Punchblock::Event::Complete::Hangup name=:hangup, call_id="ztj99ye-lx7-v6lxsvdobtanb", component_id="ab2b0f00-f158-4f5f-8dc0-5f74cf12d43c">, recording=#<Punchblock::Component::Record::Recording uri="file:/tmp/rayo4781399191081109846.wav", duration=100, size=3898, call_id="ztj99ye-lx7-v6lxsvdobtanb", component_id="ab2b0f00-f158-4f5f-8dc0-5f74cf12d43c">, call_id="ztj99ye-lx7-v6lxsvdobtanb", component_id="ab2b0f00-f158-4f5f-8dc0-5f74cf12d43c">
[2012-03-14 17:47:53] DEBUG Adhearsion::Call: ztj99ye-lx7-v6lxsvdobtanb: Receiving message: #<Punchblock::Event::End reason=:hangup, headers_hash={}, call_id="ztj99ye-lx7-v6lxsvdobtanb", component_id=nil>
```

**Comment by benlangfeld** [comment]
I'm going to pre-empt @mpermar here and request PRISM logs for the corresponding session

**Comment by bklang** [comment]
PRISM logs: https://gist.github.com/f6ab2a5f50366c04276a

**Comment by benlangfeld** [comment]
The recording is sent, and is right there in the paste

**Comment by loopingrage** [comment]
Opened an internal issue...
